# Supabase Configuration

[auth]
enabled = true
site_url = "http://localhost:8080"
additional_redirect_urls = ["https://localhost:8080"]
jwt_expiry = 3600
disable_signup = false

[api]
enabled = true
port = 54321
schemas = ["public", "auth"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 6543
shadow_port = 54320
major_version = 15

[studio]
port = 54323

# Enable/disable individual extensions
[extensions]
http = true
pg_graphql = true
pg_jsonschema = true 